### ISSUE TITLE
Config file is being saved on every invocation of the CLI

### ISSUE THREAD

**Issue by Kumm-Kai** [stackitcloud/stackit-cli#153]
Currently, the STACKIT CLI calls the [`config.InitConfig`](https://github.com/stackitcloud/stackit-cli/blob/main/internal/pkg/config/config.go#L69) function on every invocation.

On the very first call of the binary (no `.stackit` directory exists), it creates the directory and a config file (with default values).
On every following binary call the config file is being read **and** directly written to disk again.

This is probably only problematic in some small edge cases, like calling `stackit` multiple times in one command using `process substiution` (e.g., `<(stackit xyz)`). In this case the CLI fails because `viper.WriteConfigAs` is not concurrency-safe.

This can be solved by either:
1. Only creating the directory & config file if it is actually needed, e.g., when calling `stackit config set/unset`
2. Only writing the config file when necessary (e.g., file on disk differs from config in memory)

From my point of view the first solution would be the best one because in my opinion there is no need to create a config file if the user didn't change the defaults.

**Comment by joaopalet** [comment]
Hi @Kumm-Kai,
Thanks for the suggestion! This was addressed in the PR linked above and will be included in the next release.

**Comment by Kumm-Kai** [comment]
Great, thanks for looking into it @joaopalet ❤️

solved by 81b75942e3c381edccd93277db3144ab6910eb4b

**Comment by Kumm-Kai** [comment]
#185 doesn't completely solve this issue. A empty file is still being created on the very first invocation.
This still results in failures when using process substiution.
I would propose only creating the file **and** directory if something should actually be written.

If you want to I can open a PR for it.

**Comment by joaopalet** [comment]
Ah good point, I though the issue was only in `viper.WriteConfigAs`.

If you want to raise the PR making the fix I would be happy to review and support, otherwise I will try to do it within the next few days.

**Comment by joaopalet** [comment]
This was addressed in #214 and will be included in the next release.

Thanks @Kumm-Kai for the contribution 💪
